### ISSUE TITLE
Site fails with an error message when deployed

### ISSUE THREAD

**Issue by stevehobbsdev** [thehobbs/wedding-rsvp#15]
I recovered the logs from Heroku, looks like it is just the Postgres config:

```
2016-03-06T20:33:22.280157+00:00 app[web.1]:                ORDER BY a.attnum
2016-03-06T20:33:22.280158+00:00 app[web.1]: ):
2016-03-06T20:33:22.280158+00:00 app[web.1]:   app/controllers/home_controller.rb:4:in `index'
2016-03-06T20:33:22.280159+00:00 app[web.1]: 
2016-03-06T20:33:22.280159+00:00 app[web.1]: 
2016-03-06T21:07:18.948386+00:00 heroku[web.1]: Idling
2016-03-06T21:07:18.949112+00:00 heroku[web.1]: State changed from up to down
2016-03-06T21:07:18.954267+00:00 heroku[web.1]: State changed from down to starting
2016-03-06T21:07:20.840419+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 25071 -e production`
2016-03-06T21:07:21.895717+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-03-06T21:07:22.587338+00:00 app[web.1]: [2016-03-06 21:07:22] FATAL SignalException: SIGTERM
2016-03-06T21:07:22.587352+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:177:in `select'
2016-03-06T21:07:22.587354+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:177:in `block in start'
2016-03-06T21:07:22.587355+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:33:in `start'
2016-03-06T21:07:22.587355+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:164:in `start'
2016-03-06T21:07:22.587356+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
2016-03-06T21:07:22.587357+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
2016-03-06T21:07:22.587357+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/server.rb:80:in `start'
2016-03-06T21:07:22.587359+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2016-03-06T21:07:22.587359+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
2016-03-06T21:07:22.587360+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
2016-03-06T21:07:22.587361+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2016-03-06T21:07:22.587361+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
2016-03-06T21:07:22.587363+00:00 app[web.1]:    bin/rails:9:in `require'
2016-03-06T21:07:22.587363+00:00 app[web.1]:    bin/rails:9:in `<main>'
2016-03-06T21:07:22.587513+00:00 app[web.1]: [2016-03-06 21:07:22] INFO  going to shutdown ...
2016-03-06T21:07:22.587650+00:00 app[web.1]: [2016-03-06 21:07:22] INFO  WEBrick::HTTPServer#start done.
2016-03-06T21:07:22.587697+00:00 app[web.1]: Exiting
2016-03-06T21:07:23.354927+00:00 app[web.1]: [2016-03-06 21:07:23] INFO  WEBrick 1.3.1
2016-03-06T21:07:23.354969+00:00 app[web.1]: [2016-03-06 21:07:23] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
2016-03-06T21:07:23.355214+00:00 app[web.1]: [2016-03-06 21:07:23] INFO  WEBrick::HTTPServer#start: pid=3 port=25071
2016-03-06T21:07:23.441222+00:00 heroku[web.1]: Process exited with status 143
2016-03-06T21:07:23.742635+00:00 heroku[web.1]: State changed from starting to up
2016-03-06T21:39:55.197341+00:00 heroku[web.1]: Idling
2016-03-06T21:39:55.197942+00:00 heroku[web.1]: State changed from up to down
2016-03-06T21:39:59.920234+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-03-06T21:40:02.487523+00:00 heroku[web.1]: Process exited with status 143
2016-03-06T21:40:01.334042+00:00 app[web.1]: [2016-03-06 21:40:01] FATAL SignalException: SIGTERM
2016-03-06T21:40:01.334055+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:177:in `select'
2016-03-06T21:40:01.334056+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:177:in `block in start'
2016-03-06T21:40:01.334057+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:33:in `start'
2016-03-06T21:40:01.334058+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:164:in `start'
2016-03-06T21:40:01.334058+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
2016-03-06T21:40:01.334059+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
2016-03-06T21:40:01.334060+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/server.rb:80:in `start'
2016-03-06T21:40:01.334061+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2016-03-06T21:40:01.334062+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
2016-03-06T21:40:01.334062+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
2016-03-06T21:40:01.334063+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2016-03-06T21:40:01.334064+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
2016-03-06T21:40:01.334065+00:00 app[web.1]:    bin/rails:9:in `require'
2016-03-06T21:40:01.334066+00:00 app[web.1]:    bin/rails:9:in `<main>'
2016-03-06T21:40:01.334089+00:00 app[web.1]: [2016-03-06 21:40:01] INFO  going to shutdown ...
2016-03-06T21:40:01.334130+00:00 app[web.1]: [2016-03-06 21:40:01] INFO  WEBrick::HTTPServer#start done.
2016-03-06T21:40:01.334161+00:00 app[web.1]: => Booting WEBrick
2016-03-06T21:40:01.334163+00:00 app[web.1]: => Rails 4.2.4 application starting in production on http://0.0.0.0:25071
2016-03-06T21:40:01.334163+00:00 app[web.1]: => Run `rails server -h` for more startup options
2016-03-06T21:40:01.334164+00:00 app[web.1]: => Ctrl-C to shutdown server
2016-03-06T21:40:01.334166+00:00 app[web.1]: Exiting
2016-03-08T17:36:03.603366+00:00 heroku[web.1]: Unidling
2016-03-08T17:36:03.603852+00:00 heroku[web.1]: State changed from down to starting
2016-03-08T17:36:06.104416+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 42300 -e production`
2016-03-08T17:36:10.711705+00:00 heroku[web.1]: State changed from starting to up
2016-03-08T17:36:10.594028+00:00 app[web.1]: [2016-03-08 17:36:10] INFO  WEBrick 1.3.1
2016-03-08T17:36:10.594051+00:00 app[web.1]: [2016-03-08 17:36:10] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
2016-03-08T17:36:10.602510+00:00 app[web.1]: [2016-03-08 17:36:10] INFO  WEBrick::HTTPServer#start: pid=3 port=42300
2016-03-08T17:36:11.654122+00:00 app[web.1]: => Booting WEBrick
2016-03-08T17:36:11.654135+00:00 app[web.1]: => Rails 4.2.4 application starting in production on http://0.0.0.0:42300
2016-03-08T17:36:11.654136+00:00 app[web.1]: => Run `rails server -h` for more startup options
2016-03-08T17:36:11.654137+00:00 app[web.1]: => Ctrl-C to shutdown server
2016-03-08T17:36:11.654138+00:00 app[web.1]: Started GET "/" for 82.146.145.178 at 2016-03-08 17:36:11 +0000
2016-03-08T17:36:11.744034+00:00 app[web.1]: Processing by HomeController#index as HTML
2016-03-08T17:36:11.756377+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "guest_details" does not exist
2016-03-08T17:36:11.756393+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"guest_details"'::regclas...
2016-03-08T17:36:11.756394+00:00 app[web.1]:                                           ^
2016-03-08T17:36:11.756395+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-03-08T17:36:11.756396+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2016-03-08T17:36:11.756396+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-03-08T17:36:11.756397+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-03-08T17:36:11.756398+00:00 app[web.1]:                WHERE a.attrelid = '"guest_details"'::regclass
2016-03-08T17:36:11.756398+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-03-08T17:36:11.756399+00:00 app[web.1]:                ORDER BY a.attnum
2016-03-08T17:36:11.756400+00:00 app[web.1]: 
2016-03-08T17:36:11.756617+00:00 app[web.1]: Completed 500 Internal Server Error in 12ms (ActiveRecord: 2.7ms)
2016-03-08T17:36:11.757626+00:00 app[web.1]: 
2016-03-08T17:36:11.757635+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "guest_details" does not exist
2016-03-08T17:36:11.757636+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"guest_details"'::regclas...
2016-03-08T17:36:11.757636+00:00 app[web.1]:                                           ^
2016-03-08T17:36:11.757637+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-03-08T17:36:11.757638+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2016-03-08T17:36:11.757638+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-03-08T17:36:11.757639+00:00 app[web.1]:                WHERE a.attrelid = '"guest_details"'::regclass
2016-03-08T17:36:11.757639+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-03-08T17:36:11.757640+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-03-08T17:36:11.757641+00:00 app[web.1]:                ORDER BY a.attnum
2016-03-08T17:36:11.757641+00:00 app[web.1]: ):
2016-03-08T17:36:11.757642+00:00 app[web.1]:   app/controllers/home_controller.rb:4:in `index'
2016-03-08T17:36:11.757643+00:00 app[web.1]: 
2016-03-08T17:36:11.757643+00:00 app[web.1]: 
2016-03-08T17:36:11.759371+00:00 heroku[router]: at=info method=GET path="/" host=hobbs-wedding-rsvp.herokuapp.com request_id=d6d96c72-56ac-428e-ad97-a1542ab05136 fwd="82.146.145.178" dyno=web.1 connect=0ms service=110ms status=500 bytes=1754
2016-03-08T17:36:12.026827+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=hobbs-wedding-rsvp.herokuapp.com request_id=355d6e04-327d-41f9-a21f-fcf8e6e5ecf5 fwd="82.146.145.178" dyno=web.1 connect=0ms service=4ms status=200 bytes=228
```

**Comment by stevehobbsdev** [comment]
Fixed in e6d672f
